import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Noto Sans JPフォントの設定
// - weight: フォントの太さを 400 (Regular) と 700 (Bold) に設定
// - subsets: ラテン文字のサブセットを使用
const fontNnotoSansJP = Noto_Sans_JP({
  weight: ["400", "700"], // ※不要な weight は読み込まなくなるためバンドルサイズが小さくなり、読み込みを高速化させる。
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={cn(fontNnotoSansJP.className, "bg-background antialiased min-h-screen")}>
        {children}
      </body>
    </html>
  );
}
